Feature/analysis export
the-deep/server pull request #1095
Opened 2022-05-16 06:12 UTC by k9845

Addresses 
- Analysis Export(https://github.com/the-deep/server/issues/1091)

## Changes
- Add mutation for analysis export

Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2022-05-16 10:08 UTC, thenav56 requested changes

2022-05-16 10:08 UTC, thenav56 commented on apps/export/analyses/excel_exporter.py
> +        for analytical_statement_entry in analytical_statement_entries:
Let's use iterator for analytical_statement_entries

2022-05-16 10:08 UTC, thenav56 commented on apps/export/analyses/excel_exporter.py
> +            url = f'{settings.HTTP_PROTOCOL}://{settings.DEEPER_FRONTEND_HOST}/permalink/projects/'
Let's create a function for this. Maybe define a file like deep/premalinks.py and define permalink patterns and functions there.

2022-05-16 10:08 UTC, thenav56 commented on apps/export/serializers.py
> +            if analysis_object.project != project:
```suggestion
            if analysis_object.project != self.project:
```

2022-05-16 10:08 UTC, thenav56 commented on apps/export/serializers.py
> +                )
We can move this to validate_analysis

2022-05-16 10:08 UTC, thenav56 commented on apps/export/serializers.py
> +        data['analysis'] = data.get('analysis')
```suggestion
```

2022-05-16 10:08 UTC, thenav56 commented on apps/export/tasks/tasks_analyses.py
> +    print(analytical_statement_entries, "*******************")
```suggestion
```

2022-05-16 10:08 UTC, thenav56 commented on apps/export/tasks/tasks_analyses.py
> +            '(Entries Export) Unkown Export Type Provided: {export_type} for Export: {export.id}'
```suggestion
           f'(Entries Export) Unkown Export Type Provided: {export_type} for Export: {export.id}'
```

2022-05-16 10:08 UTC, thenav56 commented on apps/export/tests/test_mutations.py
> +
Where is test for file check?

2022-05-20 04:21 UTC, k9845 commented on apps/export/tests/test_mutations.py
> +
Added `TODO`

2022-05-20 05:07 UTC, thenav56 requested changes

2022-05-20 05:07 UTC, thenav56 commented on apps/export/analyses/excel_exporter.py
> +
```suggestion
```

2022-05-20 05:07 UTC, thenav56 commented on apps/export/serializers.py
> +        return analysis
```suggestion
        if analysis=.project != self.project:
            raise serializers.ValidationError(
                f'Analysis project {analysis.project_id} doesn\'t match current project {self.project.id}'
            )
        return analysis
```

2022-05-20 05:07 UTC, thenav56 commented on apps/export/analyses/excel_exporter.py
> +        for analytical_statement_entry in analytical_statement_entries.iterator():
Add select_related and prefetch_related as required.

2022-05-20 05:07 UTC, thenav56 commented on apps/export/tests/test_mutations.py
> +
Wow

2022-05-20 05:29 UTC, thenav56 approved these changes

2022-05-20 05:55 UTC, merged