Add test case for PDNA and Humanitarian response
the-deep/server pull request #1102
Opened 2022-05-23 11:46 UTC by Rup-Narayan-Rajbanshi

Addresses Unified Connector

## Changes

- Add api for atom feed fields
- Add test case for humaniterian response and PDNA

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [x] permission checks (tests here too)
- [x] translations

2022-05-31 05:45 UTC, bimal125 requested changes

2022-05-31 05:45 UTC, bimal125 commented on apps/unified_connector/tests/mock_data/humanitarian_response_mock_data.py
> +    {
What if www.humanitarianresponse.info deleted the pdf file?

2022-05-31 10:23 UTC, Rup-Narayan-Rajbanshi commented on apps/unified_connector/tests/mock_data/humanitarian_response_mock_data.py
> +    {
> What if [www.humanitarianresponse.info](http://www.humanitarianresponse.info) deleted the pdf file?

if so, url will be none if no url is present.

2022-06-01 08:53 UTC, AdityaKhatri approved these changes

2022-06-01 08:53 UTC, merged