Export title rename
the-deep/server pull request #1148
Opened 2022-07-14 05:05 UTC by thenav56

## Changes

- Add ExportUpdateMutation.
- For S3 storage. Add filename in generated signed url.

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [ ] permission checks (tests here too)
- [ ] translations

2022-07-18 07:47 UTC, k9845 requested changes

2022-07-18 07:47 UTC, k9845 commented on apps/export/tests/test_mutations.py
> +        self.assertEqual(response['project']['exportCreate']['result'], None, response)
```suggestion
        self.assertEqual(response['project']['exportUpdate']['result'], None, response)
```

2022-07-18 07:47 UTC, k9845 commented on apps/export/tests/test_mutations.py
> +        response_export = response['project']['exportCreate']['result']
```suggestion
        response_export = response['project']['exportUpdate']['result']
```

2022-07-22 05:36 UTC, tnagorra approved these changes

2022-07-22 05:36 UTC, merged