Feature/project logs
the-deep/server pull request #1163
Opened 2022-08-22 09:08 UTC by thenav56

Addresses
- #1112

## Changes

- Add project log in
    - Project Create
    - Project Mutations (utils.graphene.middleware::ProjectLogMiddleware)
        - Project Update
        - Project Membership
            - User
            - Usergroup
        - Project Region
        - Project Viz share configuration.
        - Project Join request accept.
        - Project Delete (Soft)
- Add/Update test.
- Admin Panel.
    - Add ProjectChangeLog Model.
    - Add auto complete filters in entry/lead.
Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2022-08-24 12:47 UTC, bewakes requested changes

2022-08-24 12:47 UTC, bewakes commented on apps/project/admin.py
> +    @admin.display(description='Diff prettry JSON')
`prettry` means `pretty`?

2022-08-24 12:47 UTC, bewakes commented on apps/project/change_log.py
> +def get_flat_dict_diff(list1, list2, fields):
Please add argument types wherever possible, especially for utils functions like this.

2022-08-25 03:10 UTC, thenav56 commented on apps/project/change_log.py
> +def get_flat_dict_diff(list1, list2, fields):
Done

2022-08-25 03:10 UTC, thenav56 commented on apps/project/admin.py
> +    @admin.display(description='Diff prettry JSON')
Done

2022-08-25 04:08 UTC, k9845 approved these changes

2022-08-25 04:41 UTC, bewakes approved these changes

2022-11-07 04:43 UTC, merged