Add total source count of all connectors
the-deep/server pull request #1165
Opened 2022-08-24 05:40 UTC by Rup-Narayan-Rajbanshi

Addresses Unified connectors

## Changes

-Add total source count of all connectors

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] tests
- [x] permission checks (tests here too)
- [ ] translations

2022-08-24 11:09 UTC, thenav56 requested changes
Looks good just view a few comments.

2022-08-24 11:09 UTC, thenav56 commented on apps/unified_connector/schema.py
> +    return
We don't have to do the count operation if the user doesn't have permission.

```suggestion
def get_total_source(info):
    qs = ConnectorSourceLead.objects.filter(source__unified_connector__project=info.context.active_project)
    if PP.check_permission(info, PP.Permission.VIEW_UNIFIED_CONNECTOR):
        return qs.count()
    return
```

2022-08-24 11:09 UTC, thenav56 commented on apps/unified_connector/schema.py
> +        return get_total_source(info)
This should be fine here.
```suggestion
           qs = ConnectorSourceLead.objects.filter(source__unified_connector__project=info.context.active_project)
           if PP.check_permission(info, PP.Permission.VIEW_UNIFIED_CONNECTOR):
               return qs.count()
           return
```

2022-08-25 07:06 UTC, thenav56 approved these changes

2022-09-07 03:54 UTC, AdityaKhatri commented
Closed because: https://github.com/the-deep/server/pull/1169

2022-09-07 03:54 UTC, closed without merging