Feature/project by leads
the-deep/server pull request #1272
Opened 2023-02-13 09:48 UTC by thenav56

Addresses
- https://github.com/the-deep/server/issues/1271

## Changes

* Add projects by leads

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2023-02-27 04:45 UTC, AdityaKhatri requested changes

2023-02-27 04:45 UTC, AdityaKhatri commented on apps/deep_explore/tasks.py
>          projectsCountByMonth {
Remove projectsCountByMonth, leadsCountByMonth, leadsCountByDay, entriesCountByRegion, entriesCountByMonth

2023-02-27 04:45 UTC, AdityaKhatri commented on apps/deep_explore/tasks.py
>          totalActiveUsers
Add leadsCountByDay, entriesCountByRegion

2023-02-28 06:05 UTC, bewakes submitted a review, later dismissed
Looks good to me. Great work!
Only that if possible the migrations can be merged to one.

2023-02-28 06:21 UTC, k9845 approved these changes

2023-03-02 04:35 UTC, merged