Implement graphql mutation node for delete lead in bulk #1459
the-deep/server pull request #1460
Opened 2024-04-04 08:57 UTC by susilnem

Addresses [Implement graphql mutation node for delete lead in bulk](https://github.com/the-deep/server/issues/1459)

## Changes
-  Add mutation for bulk delete
- Generate schema

Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2024-04-08 10:04 UTC, thenav56 commented
@susilnem, I  think this is almost already done, We just need to add a new line and some test cases.

https://github.com/the-deep/server/blob/develop/apps/lead/mutation.py#L92-L101
https://github.com/the-deep/server/blob/develop/apps/entry/mutation.py#L69

2024-04-09 05:55 UTC, k9845 requested changes

2024-04-09 05:55 UTC, k9845 commented on apps/lead/tests/test_mutations.py
> +        self.assertEqual(lead_count - 2, Lead.objects.count())
Make sure to add test for different user with different permission.
Also Instead of count, let's assert for id.

2024-05-30 04:05 UTC, thenav56 requested changes
Looks good. Let's add more cases to the test.

2024-05-30 04:05 UTC, thenav56 commented on apps/lead/tests/test_mutations.py
> +        self.assertMatchSnapshot(result, 'success')
This is not required (same as next line)
> NOTE: For simple field check, we don't need snapshot test.

2024-05-30 04:05 UTC, thenav56 commented on apps/lead/tests/test_mutations.py
> +                    dict(title=lead2.title),
Let's add id as well

2024-05-30 04:05 UTC, thenav56 commented on apps/lead/tests/test_mutations.py
> +        member_user = UserFactory.create()
Let's add readonly_member_user as well.

2024-05-30 04:05 UTC, thenav56 commented on apps/lead/tests/test_mutations.py
> +        self.assertEqual(lead_count, Lead.objects.count())
Let's do this after each _query_check

2024-05-31 03:54 UTC, thenav56 requested changes

2024-05-31 03:54 UTC, thenav56 commented on apps/lead/tests/test_mutations.py
> +        self.assertEqual(lead_count, Lead.objects.count())
```suggestion
```

2024-06-05 06:03 UTC, thenav56 requested changes

2024-06-05 06:03 UTC, thenav56 commented on apps/lead/tests/test_mutations.py
> +        )
Let's add a final
```suggestion
        )
        self.assertEqual(0, Lead.objects.count())
```

2024-06-05 06:23 UTC, thenav56 commented on apps/lead/tests/test_mutations.py
> +        lead2 = LeadFactory.create(project=project)
Add other nose lead

2024-06-05 06:24 UTC, thenav56 commented on apps/lead/tests/test_mutations.py
> +        lead1 = LeadFactory.create(project=project)
Use create_batch batch_create. use 3

2024-06-07 06:17 UTC, thenav56 approved these changes, later dismissed

2024-08-23 05:40 UTC, sudan45 submitted a review, later dismissed

2024-09-20 04:43 UTC, merged