Fix pinned projects appearing for other user
the-deep/server pull request #1490
Opened 2024-05-16 06:22 UTC by sudan45

Addresses 
 - https://github.com/the-deep/server/pull/1489

Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2024-05-16 09:10 UTC, susilnem approved these changes

2024-05-22 04:08 UTC, thenav56 requested changes

2024-05-22 04:08 UTC, thenav56 commented on apps/project/tests/test_schemas.py
> +        non_member_user = UserFactory.create()
We aren't checking any membership logic here, let's use proper naming.

```suggestion
        user1 = UserFactory.create()
        user2 = UserFactory.create()
```

2024-05-22 04:08 UTC, thenav56 commented on apps/project/tests/test_schemas.py
> +            query MyQuery {
Let's try to use all the fields we can use for pin projects.

2024-05-27 08:15 UTC, merged