Add LeadreviewAttachment Model
the-deep/server pull request #1505
Opened 2024-06-06 18:15 UTC by sudan45

Addresses https://github.com/the-deep/server/issues/1493

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2024-06-07 06:13 UTC, thenav56 requested changes
Looks good

2024-06-07 06:13 UTC, thenav56 commented on apps/lead/models.py
> +        IMAGE = 'image', 'Image'
Let's use IntergerChoices.  (Use PositiveSmallIntegerField as field)

2024-06-07 06:13 UTC, thenav56 commented on apps/lead/tests/test_apis.py
> +            'tables_path': [],
Is this required?

2024-06-07 06:13 UTC, thenav56 commented on apps/lead/migrations/0050_auto_20240606_0608.py
> +        ),
We aren't deleting old model, just changing it

2024-06-07 06:13 UTC, thenav56 commented on apps/lead/schema.py
> +            'type',
We need to manually define enum class in enums.py and use it for the enum field here

2024-06-07 06:13 UTC, thenav56 commented on apps/lead/schema.py
> +            'file_preview',
Not required here

2024-06-07 06:13 UTC, thenav56 commented on apps/lead/schema.py
> +    lead_preview_attachments = graphene.List(graphene.NonNull(LeadPreviewAttachmentsType))
```suggestion
    lead_preview_attachments = graphene.List(graphene.NonNull(LeadPreviewAttachmentsType), required=True)
```

2024-06-07 06:13 UTC, thenav56 commented on apps/lead/schema.py
> +class LeadPreviewAttachmentsType(DjangoObjectType):
```suggestion
class LeadPreviewAttachmentType(DjangoObjectType):
```

2024-06-07 06:13 UTC, thenav56 commented on apps/deepl_integration/serializers.py
> +        default=[]
```suggestion
        default=[],
```

2024-06-07 06:13 UTC, thenav56 commented on apps/deepl_integration/serializers.py
>                  data.get('images_path', [])[:10],   # TODO: Support for more images, too much image will error.
@AdityaKhatri @subinasr Do we will need to change this?

2024-06-07 06:13 UTC, thenav56 commented on apps/deepl_integration/handlers.py
> +        images = [dict(item) for item in images_uri]
Let's do this on serializer, from function typing it should be list of dict

2024-06-10 08:51 UTC, thenav56 requested changes

2024-06-10 08:51 UTC, thenav56 commented on apps/entry/serializers.py
> +                    file=lead_attachment.file,
Let's clone the file as well. If LeadPreviewAttachment is deleted, we need to persist entry attachment data.

2024-06-10 08:51 UTC, thenav56 commented on apps/entry/models.py
> +    class EntryFileType(models.IntegerChoices):
Let's add a NOTE on entry will reference it using entry_attachment

2024-06-10 08:51 UTC, thenav56 commented on apps/entry/models.py
> +        default=EntryFileType.XLSX
```suggestion
        default=EntryFileType.XLSX,
```

2024-06-10 08:51 UTC, thenav56 commented on apps/entry/schema.py
> +            'client_id', 'entry_attachment'
```suggestion
            'client_id',
```

2024-06-10 08:51 UTC, thenav56 commented on apps/entry/schema.py
> +    file_preview = graphene.Field(FileFieldType)
```suggestion
    file = graphene.Field(FileFieldType, required=True)
    file_preview = graphene.Field(FileFieldType, required=True)
```

2024-06-10 08:51 UTC, thenav56 commented on apps/entry/schema.py
> +
Let's add 
```suggestion
       only_fields = ('id',)
```

2024-06-10 08:51 UTC, thenav56 commented on apps/entry/migrations/0038_auto_20240609_0904.py
Let's squash all the migrations before merging.

Let's do this at the end
- Revert back all changes
- Delete all files
- Re-create single migration

2024-06-10 08:51 UTC, thenav56 commented on apps/entry/admin.py
> +admin.site.register(EntryAttachment)
Let's add this as autocomplete in Entry admin model

2024-06-10 08:51 UTC, thenav56 commented on apps/lead/models.py
> +        default=AttachementFileType.XLSX
```suggestion
        default=AttachementFileType.XLSX,
```

2024-06-10 08:51 UTC, thenav56 commented on apps/lead/models.py
>          return 'Image extracted for {}'.format(self.lead)
```suggestion
        return 'Image extracted for {}'.format(self.lead.pk)
```

2024-06-10 08:51 UTC, thenav56 commented on apps/lead/schema.py
> +    type = graphene.Field(LeadPreviewAttachmentTypeEnum)
```suggestion
    file = graphene.Field(FileFieldType, required=True)
    file_preview = graphene.Field(FileFieldType, required=True)
    type = graphene.Field(LeadPreviewAttachmentTypeEnum, required=True)
```

2024-06-10 08:51 UTC, thenav56 commented on apps/lead/schema.py
> +    lead_preview_attachment = graphene.List(graphene.NonNull(LeadPreviewAttachmentType), required=True)
```suggestion
    lead_preview_attachments = graphene.List(graphene.NonNull(LeadPreviewAttachmentType), required=True)
```

2024-06-10 08:51 UTC, thenav56 commented on apps/deepl_integration/serializers.py
> +    tables_path = serializers.ListSerializer(child=TablePathSerializer(required=False))
```suggestion
    images_path = serializers.ListSerializer(child=ImagePathSerializer(required=True), required=False)
    tables_path = serializers.ListSerializer(child=TablePathSerializer(required=True), required=False)
```

Also, let's check this behavior if user can send Null.

2024-06-10 08:51 UTC, thenav56 commented on apps/deepl_integration/serializers.py
> +    )
Check this behavior, will there be image if there is page_number?

2024-06-10 08:51 UTC, thenav56 commented on apps/entry/schema.py
> +
Let's add a type for the enum

2024-06-10 08:51 UTC, thenav56 commented on apps/deepl_integration/handlers.py
> +                        image_obj
```suggestion
```suggestion
                        os.path.join(
                            attachement_base_path,
                            os.path.basename(urlparse(image).path),
                         ),
                         image_obj,
```
```

2024-06-10 08:51 UTC, thenav56 commented on apps/deepl_integration/handlers.py
> +                lead_attachement.save()
```suggestion
                if image_obj:
                    lead_attachement = LeadPreviewAttachment(lead=lead)
                    ......
                    lead_attachement.save()
```

2024-06-10 08:51 UTC, thenav56 commented on apps/deepl_integration/handlers.py
> +            lead_attachement = LeadPreviewAttachment(lead=lead)
```suggestion
            if table_img:
                lead_attachement = LeadPreviewAttachment(lead=lead)
```

2024-06-10 08:51 UTC, thenav56 commented on apps/deepl_integration/handlers.py
> +            table_attahcment = RequestHelper(url=table['content_link'], ignore_error=True).get_file()
```suggestion
            table attachment = RequestHelper(url=table['content_link'], ignore_error=True).get_file()
```

2024-06-13 05:10 UTC, thenav56 requested changes

2024-06-13 05:10 UTC, thenav56 commented on apps/entry/serializers.py
> +        return lead_attachment
Isolated validations, use validate for complex checks

2024-06-13 05:10 UTC, thenav56 commented on apps/entry/serializers.py
>          image = data.get('image')
We need to handle this as well

2024-06-13 05:10 UTC, thenav56 commented on apps/lead/filter_set.py
> +    exclude_attachment_id = IDListFilter(method='filter_exclude_lead_attachment_id')
```suggestion
    exclude_attachment_ids = IDListFilter(method='filter_exclude_lead_attachment_ids')
```

2024-06-19 09:39 UTC, subinasr commented on apps/deepl_integration/serializers.py
>                  data.get('images_path', [])[:10],   # TODO: Support for more images, too much image will error.
Safar: For the time being, we can just process 10 items for tables_path as well. Just to make this consistent.
Later, we can get all of these on async fashion.

2024-06-19 09:40 UTC, subinasr commented on apps/entry/schema.py
> +    canonical_preview_image = graphene.String(required=False)
We can remove this now

2024-06-19 09:42 UTC, subinasr commented on apps/entry/serializers.py
> +                'excerpt': f'EXCERPT is required when entry_tag is {entry_type}'
The audience of these error message is the end user.

2024-06-21 04:49 UTC, susilnem approved these changes
LGTM!

2024-06-21 09:32 UTC, thenav56 requested changes

2024-06-21 09:32 UTC, thenav56 commented on apps/deepl_integration/handlers.py
> +            lead_attachment.order = connector_lead_attachment.order
Missing lead_attachmend.save()

2024-06-21 09:32 UTC, thenav56 commented on apps/unified_connector/migrations/0009_auto_20240618_0924.py
> +        ),
Danger

2024-06-27 04:00 UTC, thenav56 requested changes
Looks good.

2024-06-27 04:00 UTC, thenav56 commented on apps/lead/migrations/0051_auto_20240625_0509.py
> +        lead_attachment.type = 2  # default type is image
Let's use LeadPreviewAttachment.objects.update(.....)

2024-06-27 04:00 UTC, thenav56 commented on server.diff
Clean-up required

2024-06-27 04:00 UTC, thenav56 commented on apps/lead/migrations/0051_auto_20240625_0509.py
> +        ),
This is missing AlterField for file (`upload_to` has been changed)

2024-06-27 04:00 UTC, thenav56 commented on apps/unified_connector/migrations/0010_auto_20240625_0806.py
> +        connector_lead_attachment.type = 2  # default type is image
Use ConnectorLeadPreviewAttachment.objects.update(..)

2024-07-05 08:27 UTC, thenav56 requested changes

2024-07-05 08:27 UTC, thenav56 commented on apps/entry/migrations/0038_auto_20240609_0904.py
Delete migrations

2024-07-05 08:27 UTC, thenav56 commented on apps/entry/models.py
> +    def get_file_url(self):
Let's create a generic function, move the function to gallery/utils.py

```suggestion
    def get_file_url(obj, url):
```

2024-07-05 08:27 UTC, thenav56 commented on apps/gallery/enums.py
> +class ModuleTypeEnum(graphene.Enum):
Let's change the name to PrivateFileModuleType

2024-07-05 08:27 UTC, thenav56 commented on apps/gallery/views.py
> +class AttachmentFileView(views.APIView):
```suggestion
class PrivateModuleFileView(views.APIView):
```

2024-07-05 08:27 UTC, thenav56 commented on apps/gallery/views.py
> +        }, status=status.HTTP_403_FORBIDDEN)
Add test as well

```suggestion
        id = force_text(urlsafe_base64_decode(identifier))
        obj = None

        if module == ModuleTypeEnum.ENTRY_ATTACHMENT.value:
            obj = get_object_or_404(EntryAttachment, id=id)
            # Permission check here........
            # EntryAttacment->Entry->Project is member
            # EntryAttacment->Entry->Lead->confidently has access
            # - Check project & visibility permission

        if obj:
            return redirect(request.build_absolute_uri(obj.file.url))
        return response.Response({
            'error': 'Access Forbidden or File does\'t exists, Contact Admin',
        }, status=status.HTTP_403_FORBIDDEN)
```

2024-07-05 08:27 UTC, thenav56 commented on apps/lead/migrations/0051_auto_20240625_0509.py
> +        type=2,
```suggestion
        type=2,  # Image
```

2024-07-05 08:27 UTC, thenav56 commented on apps/unified_connector/migrations/0010_auto_20240625_0806.py
> +        type=2,
```suggestion
        type=2,  # Image
```

2024-07-05 08:27 UTC, thenav56 commented on apps/entry/schema.py
> +    lead_attachment_id = graphene.ID(required=True)
```suggestion
    lead_attachment_id = graphene.ID(required=False)
```

2024-07-05 08:27 UTC, thenav56 commented on apps/lead/schema.py
> +
We need this
```suggestion
        @staticmethod
        def get_custom_queryset(queryset, info, **kwargs):
            return get_lead_preview_attachment_qs(info)
```

2024-07-05 08:27 UTC, thenav56 commented on apps/lead/schema.py
> +
We need custom resolver as well

```suggestion
    @staticmethod
    def resolve_lead_preview_attachments(root, info, **kwargs) -> QuerySet:
        return get_lead_preview_attachment_qs(info)
```

2024-07-05 10:38 UTC, thenav56 requested changes

2024-07-05 10:38 UTC, thenav56 commented on apps/gallery/utils.py
> +def get_private_file_url(obj, id):
Let's change obj to `private_file_module_type: PrivateFileModuleType`

Call this function without .value, the function should do the .value internally

2024-07-05 10:38 UTC, thenav56 commented on deep/urls.py
> +        'external/private-file/<str:module>/<str:identifier>',
```suggestion
        'external/private-file/<str:module>/<str:identifier>/<filename>',
```
> NOTE: filename is only for human consumption

2024-07-05 10:38 UTC, thenav56 commented on apps/gallery/tests/test_apis.py
> +        self.lead = Lead.objects.create(project=Project)
3 types of leads by confidentiality

2024-07-05 10:38 UTC, thenav56 commented on apps/gallery/tests/test_apis.py
> +        self.assert_200(response)
this should be 403

2024-07-05 10:38 UTC, thenav56 commented on apps/gallery/tests/test_apis.py
> +        self.user = User.objects.create_user(username='testuser', password='testpassword')
3 types of users.
- Normal
- Member (Non-confidentiality)
- Member (confidentiality)

2024-07-05 10:38 UTC, thenav56 commented on apps/gallery/tests/test_apis.py
> +    def test_access_by_authenticated_user(self):
To check
- Non-logged in -> 403?
- Normal User -> 403
- Member (N-C) -> 403
- Member (C) -> 200

For id > 1000000 -> all should be 403

2024-07-05 10:38 UTC, thenav56 commented on apps/entry/models.py
> +    def get_file_url(self):
Clean-up

2024-07-05 10:38 UTC, thenav56 commented on apps/gallery/views.py
> +            obj.entry.get_for(user)
Need to make sure this work.

2024-07-09 01:44 UTC, thenav56 requested changes

2024-07-09 01:44 UTC, thenav56 commented on apps/gallery/tests/test_apis.py
> +    def test_access_by_member_user(self):
Missing member with non-confidential only permisison

2024-07-09 01:44 UTC, thenav56 commented on apps/gallery/utils.py
> +def get_private_file_url(private_file_module_type: PrivateFileModuleType, entry):
This is a generic function, we shouldn't pass entry here

```suggestion
def get_private_file_url(private_file_module_type: PrivateFileModuleType, id: int, filename: str):
```

2024-07-09 01:44 UTC, thenav56 commented on apps/gallery/utils.py
> +def check_private_entry_qs(user, project, level):
We need to update the name of this function.

With something like this
```suggestion
def check_entry_confidential_level_permisison(user, project, level):
```

2024-07-09 05:14 UTC, thenav56 approved these changes

2024-07-09 05:20 UTC, susilnem approved these changes
GTM!

2024-07-09 05:24 UTC, merged