Add Celery health check endpoint and corresponding unit tests
the-deep/server pull request #1536
Opened 2024-10-16 05:53 UTC by sudan45

Addresses 
- https://github.com/the-deep/server/issues/1512

## Feature:
- Introduced a health check endpoint (`HealthCheckView`) that allows clients to verify the status of the Celery worker.
- The endpoint responds with a "healthy" status when the worker is active and responsive, and "unhealthy" if not.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [ ] permission checks (tests here too)
- [ ] translations

2024-10-23 07:28 UTC, thenav56 commented
Let's explore this https://github.com/revsys/django-health-check
It already has ping function https://github.com/revsys/django-health-check/blob/master/health_check/contrib/celery_ping/backends.py

2024-11-22 08:33 UTC, susilnem requested changes
Minor change

2024-11-22 08:33 UTC, susilnem commented on deep/urls.py
> +    re_path(r'ht/', include('health_check.urls')),
```suggestion
    re_path(r'health-check/', include('health_check.urls')),
```

2024-11-22 11:15 UTC, susilnem approved these changes
LGTM!

2024-12-05 04:50 UTC, merged