Add status in geo area
the-deep/server pull request #1537
Opened 2024-10-23 05:15 UTC by sudan45

Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2024-11-07 07:10 UTC, susilnem requested changes
Minor changes

2024-11-07 07:10 UTC, susilnem commented on apps/geo/models.py
> +        FAILED = 'failed', 'Failed'
```suggestion
    class Status(models.IntegerChoices):
        INITIATED = 1, 'Initiated'
        PENDING = 2, 'Pending'
        COMPLETED = 3, 'Completed'
        FAILED = 4, 'Failed'
```

2024-11-07 07:10 UTC, susilnem commented on apps/geo/models.py
> +    status = models.CharField(max_length=30, choices=Status.choices, default=Status.PENDING)
```suggestion
    status = models.IntegerField(choices=Status.choices, default=Status.PENDING)
```

2024-11-07 07:10 UTC, susilnem commented on apps/geo/tasks.py
> +    region = Region.objects.get(pk=region_id)
```suggestion
    region = Region.objects.filter(pk=region_id).first()
    if not region:
      logger.error("Region not found", exc_info=True)
      return False
```

2024-11-19 05:50 UTC, AdityaKhatri requested changes

2024-11-19 05:50 UTC, AdityaKhatri commented on apps/geo/serializers.py
> +        region.status = Region.Status.INITIATED
Move this right next to action

2024-12-05 03:53 UTC, susilnem approved these changes
LGTM

2024-12-05 08:52 UTC, AdityaKhatri approved these changes

2024-12-05 09:13 UTC, Rup-Narayan-Rajbanshi requested changes
Some minor changes.

2024-12-05 09:13 UTC, Rup-Narayan-Rajbanshi commented on apps/geo/tasks.py
> +    region.save()
If we are updating just `status` field of a region we can do partial update `region.save(update_fields=['status', ])`. It reduce the overhead of saving all fields unnecessarily

2024-12-05 09:42 UTC, Rup-Narayan-Rajbanshi commented on apps/geo/tasks.py
> +    region.save()
@sudan45

2024-12-05 09:55 UTC, Rup-Narayan-Rajbanshi approved these changes

2024-12-05 10:58 UTC, merged