LLM Assisted Tagging
the-deep/server pull request #1540
Opened 2024-11-27 09:41 UTC by sudan45

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2024-12-05 08:57 UTC, Rup-Narayan-Rajbanshi commented
Lets add dependent PR link in this PR. I think this PR has dependency with https://github.com/the-deep/server/pull/1541#pullrequestreview-2480895241. @sudan45 .

2024-12-05 08:59 UTC, Rup-Narayan-Rajbanshi requested changes

2024-12-05 08:59 UTC, Rup-Narayan-Rajbanshi commented on apps/assisted_tagging/schema.py
> +        # return LLMAssistedTaggingPredication.objects.get(draft_entry=root)
Lets remove this line.

2024-12-05 08:59 UTC, Rup-Narayan-Rajbanshi commented on apps/project/serializers.py
> +        return data
We need to update this as done in this PR:https://github.com/the-deep/server/pull/1541#pullrequestreview-2480895241 Or rebase this with that branch.

2024-12-05 09:33 UTC, Rup-Narayan-Rajbanshi requested changes

2024-12-05 09:33 UTC, Rup-Narayan-Rajbanshi commented on apps/deepl_integration/handlers.py
> +        # draft_entry.save(update_fields='prediction_status')
Remove this.

2024-12-05 09:41 UTC, Rup-Narayan-Rajbanshi commented on apps/deepl_integration/handlers.py
> +        # draft_entry.save(update_fields='prediction_status')
@sudan45

2024-12-05 10:02 UTC, Rup-Narayan-Rajbanshi approved these changes

2024-12-10 05:59 UTC, thenav56 approved these changes
All good other then the geo

2024-12-10 06:08 UTC, susilnem approved these changes
GTM!

2024-12-10 06:08 UTC, susilnem approved these changes
GTM!

2024-12-10 06:13 UTC, merged