Fix login throwing validation errors
the-deep/server pull request #683
Opened 2021-02-26 08:56 UTC by k9845

#673

2021-02-27 13:11 UTC, thenav56 requested changes

2021-02-27 13:11 UTC, thenav56 commented on apps/jwt_auth/tests/test_apis.py
> +            "password": 'aass' * 130
Let's use this.
```suggestion
            "password": 'abcd' * 130
```

2021-02-27 13:11 UTC, thenav56 commented on apps/jwt_auth/serializers.py
> +        # this will now only handel max-length in login
Typo
```suggestion
        # this will now only handle max-length in the login
```

2021-03-01 05:31 UTC, thenav56 approved these changes

2021-03-01 10:39 UTC, annshress approved these changes

2021-03-02 04:20 UTC, merged