Upgrade django version
the-deep/server pull request #748
Opened 2021-04-29 10:26 UTC by bimal125

Following are main changes in this repo

- Upgraged django to latest verstion
- Setup grapql minimal

2021-05-05 04:15 UTC, thenav56 commented on apps/lead/tests/test_apis.py
> +        print(lead1.images.count(), 'the lead image count')
oh no print.

2021-05-05 04:15 UTC, thenav56 commented on apps/lead/tests/test_apis.py
> +        lead1_copy.refresh_from_db()
Not required as the `lead1_copy` is fresh.

2021-05-05 04:15 UTC, thenav56 commented on apps/lead/tests/test_apis.py
> +        print(lead1.images.count(), 'the lead image count')
oh no print.

2021-05-05 04:15 UTC, thenav56 commented on deep/settings.py
> +if DEEP_ENVIRONMENT in ['production']:
Do we need this for testing/staging servers?
Let's use `DEBUG` instead of DEEP_ENVIRONMENT if not.

2021-05-05 04:15 UTC, thenav56 commented on deploy/scripts/prod_exec.sh
> +    # fi
Let's remove this.

2021-05-05 04:15 UTC, thenav56 commented on requirements.txt
> +django-utils-six
Let's sort this.

2021-06-03 05:04 UTC, thenav56 requested changes

2021-06-03 05:04 UTC, thenav56 commented on apps/lead/tests/test_apis.py
> +        assert 2 in [item['filteredEntriesCount'] for item in response.json()['results']], response.json()
```suggestion
        assert set([1, 2]) == set([item['filteredEntriesCount'] for item in response.json()['results']], response.json())
```

2021-06-03 05:04 UTC, thenav56 commented on apps/analysis/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
Let's remove this. This is inherited from UserResource.

2021-06-03 05:13 UTC, thenav56 approved these changes

2021-06-03 10:15 UTC, k9845 approved these changes

2021-06-22 06:37 UTC, merged