Rename analytical_statement to analytical_statements
the-deep/server pull request #750
Opened 2021-04-30 05:19 UTC by tnagorra

- Add uuid in analytical_entries
- Add uuid in analytical_statements

2021-04-30 10:09 UTC, thenav56 commented
@tnagorra Both AnalyticalStatementEntry and AnalyticalStatement already have `cilent_id` field as they are inheriting the `UserResource` model. That 

https://github.com/the-deep/server/blob/9a84ece7e7883bf063282c366b810a9ec9823850/apps/user_resource/models.py#L5-L22

2021-04-30 10:11 UTC, thenav56 requested changes
@tnagorra @k9845 Both AnalyticalStatementEntry and AnalyticalStatement already have `cilent_id` field as they are inheriting the `UserResource` model.

https://github.com/the-deep/server/blob/9a84ece7e7883bf063282c366b810a9ec9823850/apps/user_resource/models.py#L5-L22

2021-04-30 10:11 UTC, thenav56 commented on apps/analysis/models.py
> +    uuid = models.CharField(max_length=255)
Not required. Let's use the already defined field `client_id`.

2021-04-30 10:11 UTC, thenav56 commented on apps/analysis/models.py
> +    uuid = models.CharField(max_length=255)
Not required. Let's use the already defined field `client_id`

2021-04-30 10:11 UTC, thenav56 commented on apps/analysis/serializers.py
> +        fields = ('id', 'uuid', 'order', 'entry')
This should work.
```suggestion
        fields = ('id', 'client_id', 'order', 'entry')
```

2021-05-03 02:58 UTC, k9845 commented on apps/analysis/serializers.py
> +        fields = ('id', 'uuid', 'order', 'entry')
Done

2021-05-03 04:31 UTC, thenav56 approved these changes

2021-05-03 09:15 UTC, annshress approved these changes

2021-05-03 10:45 UTC, merged