Add published boolean field to region model
the-deep/server pull request #832
Opened 2021-07-01 04:28 UTC by k9845

Addresses #809 

## Changes
- Added published boolean field in Region model

Mention related users here if any.
@samshara 
## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [ ] permission checks (tests here too)
- [ ] translations

2021-07-02 04:58 UTC, thenav56 requested changes

2021-07-02 04:58 UTC, thenav56 commented on apps/geo/migrations/0038_region_published.py
> +    ]
Let's merge this two migration to one.

2021-07-02 04:58 UTC, thenav56 commented on apps/geo/serializers.py
> +        if self.instance and self.instance.published == True:
```suggestion
        if self.instance and self.instance.is_published:
```

Also, add `is_published` to Meta.exclude. And add a new endpoint to publish the region.

2021-07-02 04:58 UTC, thenav56 commented on apps/geo/serializers.py
> +            raise serializers.ValidationError({'published': 'Published once set True cannot be revert back'})
```suggestion
            raise serializers.ValidationError('Published region can\'t be changed. Please contact Admin')
```
cc: @AdityaKhatri

2021-07-02 04:58 UTC, thenav56 commented on apps/geo/models.py
> +            ).exists())) and self.published == False
```suggestion
            ).exists())) and not self.is_published
```

2021-07-02 04:58 UTC, thenav56 commented on apps/geo/models.py
> +    published = models.BooleanField(default=False)
Additional work to do:
- Let's use `is_published`.
- `is_published` should be true for all current regions (we need to make sure that current regions are published)
- For new regions, `is_published` should be False by default and can be set by hitting an endpoint.

2021-07-02 07:44 UTC, thenav56 commented
@k9845 Add an endpoint to publish a region.
Also, tests are failing.

cc: @AdityaKhatri @suraj-ram-shrestha

2021-07-02 07:53 UTC, AdityaKhatri commented on apps/geo/serializers.py
> +            raise serializers.ValidationError({'published': 'Published once set True cannot be revert back'})
Looks good to me

2021-07-02 09:12 UTC, thenav56 requested changes

2021-07-02 09:12 UTC, thenav56 commented on apps/geo/models.py
> +            ).exists())) and not self.is_published
Also, move not self.is_published check to the top.

2021-07-02 09:12 UTC, thenav56 commented on apps/geo/models.py
> +        return user
Why is this here?

2021-07-02 09:12 UTC, thenav56 commented on apps/geo/serializers.py
> +        exclude = ('geo_options', 'is_published')
On second thought, remove is_published from here and add it as a read-only boolean field in the serializer.

2021-07-02 09:12 UTC, thenav56 commented on apps/geo/views.py
> +        url_path='published',
`publish` makes more sense.

```suggestion
        url_path='publish',
```

2021-07-02 09:12 UTC, thenav56 commented on apps/geo/views.py
> +        serializer_class = RegionSerializer,
Flake8, please check.

```suggestion
        serializer_class=RegionSerializer,
```

2021-07-02 09:12 UTC, thenav56 commented on apps/geo/views.py
> +        region.save()
Good habit to use updated_fields when we are changing single field only.

```suggestion
        region.save(update_fields=['is_published'])
```

2021-07-02 10:07 UTC, thenav56 requested changes

2021-07-02 10:07 UTC, thenav56 commented on apps/geo/serializers.py
> +    is_published = serializers.BooleanField(read_only=True)
Flake8.  :expressionless: 

```suggestion
    is_published = serializers.BooleanField(read_only=True)

```

2021-07-02 10:07 UTC, thenav56 commented on apps/geo/models.py
> +        return self.created_by == user
Easy to read.

```suggestion
        return user == self.created_by
```

2021-07-02 10:21 UTC, thenav56 submitted a review, later dismissed

2021-07-15 13:24 UTC, AdityaKhatri commented
Lets merge this a bit later after we diverge as this is not something we'll be implementing in the old design.

2021-09-14 18:37 UTC, annshress approved these changes, later dismissed

2021-09-23 16:28 UTC, thenav56 approved these changes

2021-09-24 05:16 UTC, merged