Fix use of union
the-deep/server pull request #839
Opened 2021-07-08 04:45 UTC by tnagorra

## Changes

* Fixes use of union

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2021-07-08 08:18 UTC, thenav56 commented
@k9845 Can you make sure all of these cases are looked upon?

![2021-07-08-140226](https://user-images.githubusercontent.com/7059255/124887823-4145b100-dff5-11eb-9ebc-73809c965d47.png)

2021-07-08 09:21 UTC, k9845 commented
@thenav56 checked with the mentioned APIs

2021-07-08 10:42 UTC, thenav56 commented on apps/project/tests/test_apis.py
> +        self.assertIn('regions', response.data)
We need to add project attributes for the union logic to kick in. Let's add that too.

2021-07-08 10:42 UTC, thenav56 requested changes

2021-07-08 10:42 UTC, thenav56 commented on apps/project/tests/test_apis.py
> +        self.assertIn('regions', response.data)
We need to add project attributes for the union logic to kick in. Let's add that too.

2021-07-09 03:43 UTC, thenav56 approved these changes

2021-07-09 04:01 UTC, tnagorra commented on apps/project/views.py
> +            regions2 = Region.get_for(request.user)
Let's add proper names
Eg: project_regions, user_regions

Let's also remove distinct from Region.objects.none()

2021-07-09 04:01 UTC, tnagorra commented on apps/project/views.py
> +                user_groups1 = UserGroup.objects.none().distinct()
Similar naming comment

2021-07-09 06:08 UTC, merged