Add boolean `is_assessment_lead` in lead model
the-deep/server pull request #865
Opened 2021-07-15 08:13 UTC by k9845

Addresses https://github.com/the-deep/server/issues/841

## Changes
 - Added `is _assessment_lead` boolean to lead model
 - Migrated all the leads that have migrations to `is _assessment_lead=True` 
Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [ ] permission checks (tests here too)
- [ ] translations

2021-07-15 08:51 UTC, thenav56 requested changes

2021-07-15 08:51 UTC, thenav56 commented on apps/lead/migrations/0037_auto_20210715_0432.py
> +        lead.save(update_fields=['is_assessment_lead'])
We should be able to use just .update() here.

Also, let's use `_set_lead_is_assessment`

2021-07-15 08:51 UTC, thenav56 commented on apps/lead/serializers.py
> +            )
We need to check if the lead already has an assessment before making it false. So,
- Always allow setting True.
- For setting False make sure there is no assessment attached to that lead.

2021-07-15 10:54 UTC, thenav56 requested changes

2021-07-15 10:54 UTC, thenav56 commented on apps/lead/migrations/0037_auto_20210715_0432.py
> +    ).update(is_assessment_lead=True)
```suggestion
def _set_lead_is_assessment(Lead):
    # Set is_assessment_lead True for lead already having assessment.
    Lead.objects.filter(assessment__isnull=False).update(is_assessment_lead=True)
```

2021-07-15 10:54 UTC, thenav56 commented on apps/lead/serializers.py
> +        return value
```suggestion
    def validate_is_assessment_lead(self, value):
        # Allow setting True
        # For False make sure there are no assessment attached.
        if value is False and hasattr(self.instance, 'assessment'):
            raise serializers.ValidationError('Lead already has an assessment.')
        return value
```

2021-07-15 12:19 UTC, thenav56 submitted a review, later dismissed

2021-07-19 10:44 UTC, bimal125 approved these changes, later dismissed

2021-09-08 15:21 UTC, thenav56 approved these changes, later dismissed

2021-09-21 06:56 UTC, merged