Refactor project-stats/summary api with 3 recent projects
the-deep/server pull request #866
Opened 2021-07-19 04:36 UTC by k9845

Addresses 
- Home page: Finalize logic for project stats time-series(#https://zube.io/deep/deep/c/3631)

## Changes
- Summary of recent 3 projects

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [] permission checks (tests here too)
- [] translations

2021-07-19 09:35 UTC, thenav56 requested changes

2021-07-19 09:35 UTC, thenav56 commented on apps/project/models.py
> +from lead.models import Lead
Let's import this inside with NOTE: to avoid circular import. And undo changes in other files.

2021-07-19 09:35 UTC, thenav56 commented on apps/project/models.py
> +    def get_change_attribute_project(user):
Let's change the function name to get_recent_active_projects. And do all the generating project queryset logic here as well.

2021-07-19 11:11 UTC, bimal125 commented on apps/project/tests/test_apis.py
> +        )
This approach will be more cleaner

data = [{"lead": lead1, "verifield": True, "months":1}, {"lead": lead2, "verifield": True, "months": 2}, ...]
for item in data:
    self.update_obj(
            self.create_entry(lead=item["lead"], verified=item["verifield", created_by=user),
            created_at=now + relativedelta(months=item["months"])
        )

2021-07-20 03:18 UTC, thenav56 requested changes

2021-07-20 03:18 UTC, thenav56 commented on apps/lead/models.py
> +    project = models.ForeignKey('project.Project', on_delete=models.CASCADE)
We don't need this change anymore.

2021-07-20 04:03 UTC, thenav56 approved these changes

2021-07-21 10:50 UTC, merged