Add schema for export
the-deep/server pull request #892
Opened 2021-08-02 05:47 UTC by k9845

Addresses 
- #https://github.com/the-deep/server/issues/885

## Changes
- Add schema for export

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [ ] permission checks (tests here too)
- [ ] translations

2021-08-02 06:44 UTC, thenav56 requested changes

2021-08-02 06:44 UTC, thenav56 commented on apps/export/schema.py
> +class ExportGQLType(DjangoObjectType):
```suggestion
class ExportType(DjangoObjectType):
```

2021-08-02 06:44 UTC, thenav56 commented on apps/export/schema.py
> +    project = graphene.ID(source='project_id')
This is not required now. We use different types for normal project objects.

2021-08-02 06:44 UTC, thenav56 commented on apps/export/factories.py
> +    project = factory.SubFactory(ProjectFactory)
Let's define this through test cases. Might be confusing when creating and trying to retrieve through a query. What do you think?

2021-08-02 06:44 UTC, thenav56 commented on apps/export/tests/test_schemas.py
> +        export = ExportFactory.create(project=project, exported_by=user)
Let's add another other_export here as well.

2021-08-02 06:44 UTC, thenav56 commented on apps/export/tests/test_schemas.py
> +        content = _query_check(export)
check for other_export as well.

2021-08-02 06:44 UTC, thenav56 commented on apps/export/tests/test_schemas.py
> +                    'status': [Export.Status.PENDING.value, Export.Status.STARTED.value]
Add a TODO: Use `self.genum(` instaed of `.value`.

2021-08-03 03:29 UTC, thenav56 requested changes

2021-08-03 03:29 UTC, thenav56 commented on apps/export/tests/test_schemas.py
> +            # TODO: Use self.genum() instaed of .value.
```suggestion
            # TODO: Use self.genum() instead of .value.
```

2021-08-03 03:30 UTC, thenav56 commented on apps/export/schema.py
> +class ExportListType(CustomDjangoListObjectType):
```suggestion
class UserExportListType(CustomDjangoListObjectType):
```

2021-08-03 11:29 UTC, thenav56 approved these changes

2021-08-04 04:46 UTC, bimal125 approved these changes

2021-08-05 03:59 UTC, merged