Add graphql endpoint for hid login
the-deep/server pull request #900
Opened 2021-08-03 10:41 UTC by k9845

Addresses https://github.com/the-deep/server/issues/837

## Changes
- Added new endpoint for hid login

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [ ] permission checks (tests here too)
- [ ] translations

2021-08-03 10:57 UTC, thenav56 requested changes

2021-08-03 10:57 UTC, thenav56 commented on apps/user/mutation.py
> +        print(serializer)
```suggestion
```

2021-08-03 10:57 UTC, thenav56 commented on apps/user/serializers.py
> +            user = humanitarian_id.get_user()
```suggestion
            return {
                'user': humanitarian_id.get_user()
            }
```

2021-08-04 09:06 UTC, thenav56 approved these changes

2021-08-05 04:17 UTC, bimal125 approved these changes

2021-08-05 04:25 UTC, merged