Add schema for lead-options in project
the-deep/server pull request #905
Opened 2021-08-04 08:47 UTC by k9845

Addresses xxxxxx (eg: #1 the-deep/server#1) \
Depends on xxxxxx (eg: #1 the-deep/server#1)

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

Mention related users here if any.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2021-08-04 09:03 UTC, thenav56 requested changes

2021-08-04 09:03 UTC, thenav56 commented on apps/project/schema.py
> +        return info.context.dl.project.lead_group.load(root.pk)
Let's define this in their respective schemas.py. We also need a single object and pagination for each query.

2021-08-04 09:03 UTC, thenav56 commented on apps/project/dataloaders.py
> +        return LeadGroupLoader(context=self.context)
Emm and lead_group are entities of lead, Let's define this loader in lead.

2021-08-06 03:48 UTC, thenav56 commented
@k9845 Rebase required with project/graphql.

2021-08-06 04:41 UTC, thenav56 requested changes

2021-08-06 04:41 UTC, thenav56 commented on apps/project/schema.py
> +
Remove this.

2021-08-06 04:41 UTC, thenav56 commented on apps/project/schema.py
> +from organization.models import OrganizationType
Remove this.

2021-08-06 04:41 UTC, thenav56 commented on apps/organization/tests/test_schemas.py
> +        content = self.query_check(query, assert_for_error=False)
`assert_for_error=False` is default value.

2021-08-06 04:41 UTC, thenav56 commented on apps/organization/tests/test_schemas.py
> +        self.assertEqual(len(content['data']['organizationTypes']['results']), 3, content)
Also assertEqual `totalCount`

2021-08-06 04:41 UTC, thenav56 commented on apps/organization/schema.py
> +    organization_types = DjangoPaginatedListObjectField(
Let's add for single organization_type also.

2021-08-06 04:41 UTC, thenav56 commented on apps/lead/factories.py
> +    project = factory.SubFactory(ProjectFactory)
Let's not define SubFactory for parent models.

2021-08-06 04:41 UTC, thenav56 commented on apps/lead/factories.py
> +    lead = factory.SubFactory(LeadFactory)
Let's not define SubFactory for parent models.

2021-08-06 04:41 UTC, thenav56 commented on apps/lead/schema.py
> +    return LeadEMMTrigger.objects.filter(lead__project=info.context.active_project)
Let's add another lead__confidentiality filter as well according to Permission.

2021-08-06 04:41 UTC, thenav56 commented on apps/lead/tests/test_schemas.py
> +        # with diffrent project
```suggestion
        # with different project
```

2021-08-06 08:57 UTC, thenav56 approved these changes

2021-08-09 04:52 UTC, bimal125 approved these changes

2021-08-09 05:12 UTC, merged