Add EntryType with queries
the-deep/server pull request #910
Opened 2021-08-09 07:18 UTC by thenav56

Addresses
- #901
- #902
- #904

## Changes

* Add EntryType.
* Add entires + entry query in project.
* Add entries query in project -> lead.

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [x] permission checks (tests here too)
- [ ] translations

2021-08-09 11:19 UTC, bimal125 requested changes

2021-08-09 11:19 UTC, bimal125 commented on apps/bulk_data_migration/management/commands/entries_highlight_migrate.py
>              print(f'Updating entries from lead chunk {n} of {total_chunks}')
Remove print statement

2021-08-09 11:21 UTC, thenav56 commented on apps/bulk_data_migration/management/commands/entries_highlight_migrate.py
>              print(f'Updating entries from lead chunk {n} of {total_chunks}')
This is intentional and legacy logic.

2021-08-09 11:32 UTC, k9845 approved these changes

2021-08-10 02:27 UTC, k9845 approved these changes

2021-08-10 02:50 UTC, bimal125 approved these changes

2021-08-10 04:35 UTC, merged