project query enhance
the-deep/server pull request #916
Opened 2021-08-12 11:15 UTC by k9845

Addresses https://github.com/the-deep/server/issues/893

## Changes
Added
  - membersCount
  - sourcesCount
  - entriesCount
  - useStatus

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [ ] permission checks (tests here too)
- [ ] translations

2021-08-16 04:08 UTC, bimal125 requested changes

2021-08-16 04:08 UTC, bimal125 commented on apps/project/tests/test_schemas.py
Lets DRY

2021-08-18 09:14 UTC, thenav56 requested changes

2021-08-18 09:14 UTC, thenav56 commented on apps/analysis_framework/schema.py
> +            return info.context.request.build_absolute_uri(root.preview_image.url)
Let's use FileField for files.

```python
from utils.graphene.fields import FileField
...
    preview_image = graphene.Field(FileField)
```

2021-08-18 09:14 UTC, thenav56 commented on apps/entry/factories.py
> +    lead = factory.SubFactory(LeadFactory)
Let's pass this manually.

2021-08-18 09:14 UTC, thenav56 commented on apps/project/models.py
> +                members_count=models.Count('members', distinct=True),
Let's calculate these using data loaders instead of annotate.

2021-08-18 09:14 UTC, thenav56 commented on apps/project/schema.py
> +            return 'non_member'
```suggestion
    @staticmethod
    def resolve_user_status(root, info):
        if root.current_user_role:
            return 'member'
        elif ProjectJoinRequest.objects.filter(
            project=root,
            requested_by=info.context.request.user,
            status='pending'
        ).exists():
            return 'pending'
        else:
            return 'non_member'
```

2021-08-18 09:14 UTC, thenav56 commented on apps/project/tests/test_schemas.py
> +            EntryFactory.create(project=public_project)
Use `create_batch`.

2021-08-19 03:31 UTC, thenav56 requested changes

2021-08-19 03:31 UTC, thenav56 commented on apps/entry/factories.py
> -
Please add a new line. To separate relative and absolute imports.

2021-08-19 03:31 UTC, thenav56 commented on apps/project/dataloaders.py
> +        from entry.models import Entry
Let's move this outside.

2021-08-19 03:31 UTC, thenav56 commented on apps/project/dataloaders.py
> +        stat_qs = Project.objects.filter(id__in=keys).annotate(
Add a `TODO: Only fetch required fields.`

2021-08-19 03:31 UTC, thenav56 commented on apps/project/schema.py
> +            'organizations', 'stats_cache', 'created_at'
Maybe also add all this.
```
            'created_at',
            'created_by',
            'modified_at',
            'modified_by',
```

2021-08-19 03:31 UTC, thenav56 commented on apps/project/schema.py
> +    user_status = graphene.Field(graphene.String)
```suggestion
    user_status = graphene.Field(graphene.String, required=True)
```

2021-08-19 03:31 UTC, thenav56 commented on apps/project/schema.py
> +            return 'non_member'
Let's use data loaders for ProjectJoinRequest to avoid n+1.

2021-08-19 03:31 UTC, thenav56 commented on apps/project/tests/test_filters.py
> +        p3.organizations.add(org1)
Looks like we can use create_batch here as well. Can you check?
```suggestion
        org1, org2, org3 = OrganizationFactory.create_batch(3)
        p1, p2, p3 = ProjectFactory.create_batch(3)
        p1.organizations.set([org2, org1])
        p2.organizations.set([org2, org3])
        p3.organizations.add(org1)
```

2021-08-19 03:31 UTC, thenav56 commented on utils/graphene/tests.py
> +    def assertQuerySetEqual(self, l1, l2):
```suggestion
    def assertQuerySetIdEqual(self, l1, l2):
```

2021-08-20 03:51 UTC, thenav56 requested changes

2021-08-20 03:51 UTC, thenav56 commented on apps/project/schema.py
> +    user_status = graphene.Field(graphene.String, required=True)
This is not required now.

2021-08-20 03:51 UTC, thenav56 commented on apps/project/tests/test_filters.py
> +        af3 = AnalysisFrameworkFactory.create()
`create_batch`

2021-08-20 03:51 UTC, thenav56 commented on apps/project/dataloaders.py
> +        return Promise.resolve([_map.get(key, 'False') for key in keys])
Why string instead of using boolean?

2021-08-20 05:54 UTC, thenav56 requested changes

2021-08-20 05:54 UTC, thenav56 commented on apps/project/schema.py
> +    @staticmethod
Remove this.

2021-08-20 05:54 UTC, thenav56 commented on apps/project/schema.py
> +    project_stats = graphene.Field(ProjectStatsType)
Remove this.

2021-08-20 05:54 UTC, thenav56 commented on apps/project/schema.py
> +    entries_count = graphene.Field(graphene.Int)
Remove this.

2021-08-20 05:54 UTC, thenav56 commented on apps/project/dataloaders.py
> +        return Promise.resolve([_map.get(key) for key in keys])
Remove this.

2021-08-20 05:54 UTC, thenav56 commented on apps/project/dataloaders.py
> +        return ProjectStatsLoader(context=self.context)
Remove this.

2021-08-20 05:54 UTC, thenav56 commented on apps/project/schema.py
> +            'organizations', 'stats_cache'
`stats_cache` Remove this.

2021-08-20 05:54 UTC, thenav56 commented on apps/project/schema.py
> +            'organizations', 'stats_cache', 'created_at', 'created_by',
Remove `stats_cache`

2021-08-20 05:54 UTC, thenav56 commented on apps/project/tests/test_filters.py
> +        p3 = ProjectFactory.create(title='towo')
Use `create_batch`

2021-08-20 05:54 UTC, thenav56 commented on apps/project/tests/test_schemas.py
> +        non_member_user = UserFactory.create()
Use `create_batch`

2021-08-20 08:48 UTC, merged