Feature/project membership mutation
the-deep/server pull request #974
Opened 2021-09-22 10:37 UTC by thenav56

Addresses
- #932
- #970

## Changes

* Add mutation for project memberships.
* Some hotfixes added.

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [ ] permission checks (tests here too)
- [ ] translations

2021-09-27 04:54 UTC, k9845 requested changes

2021-09-27 04:54 UTC, k9845 commented on utils/hid/tests/test_hid.py
> +        # ----------- Name attibute change test
```suggestion
        # ----------- Name attribute change test
```

2021-09-27 05:23 UTC, thenav56 commented on utils/hid/tests/test_hid.py
> +        # ----------- Name attibute change test
This feels like Déjà vu.

2021-09-27 07:14 UTC, k9845 approved these changes, later dismissed

2021-09-28 03:56 UTC, bimal125 submitted a review, later dismissed
looks good for me

2021-09-28 04:02 UTC, k9845 approved these changes, later dismissed

2021-09-29 08:07 UTC, k9845 approved these changes

2021-09-30 05:01 UTC, merged